import {
    createThemeContract,
    createTheme,
    globalStyle,
} from "@vanilla-extract/css";

export const vars = createThemeContract({
    color: {
        bg: null,
        bgSurface: null,
        bgSurfaceHover: null,
        bgSurfaceActive: null,
        text: null,
        textMuted: null,
        textInverse: null,
        border: null,
        borderMuted: null,
        primary: null,
        primaryHover: null,
        primaryText: null,
        danger: null,
        dangerHover: null,
        dangerText: null,
        success: null,
        successText: null,
        warning: null,
        warningText: null,
        editorBg: null,
        editorGutter: null,
        editorActiveLine: null,
        editorSelection: null,
        editorCursor: null,
        syntaxComment: null,
        syntaxKeyword: null,
        syntaxProperty: null,
        syntaxString: null,
        syntaxOperator: null,
    },
    space: {
        xs: null,
        sm: null,
        md: null,
        lg: null,
        xl: null,
        xxl: null,
    },
    radius: {
        sm: null,
        md: null,
        lg: null,
    },
    fontSize: {
        xs: null,
        sm: null,
        md: null,
        lg: null,
        xl: null,
        xxl: null,
    },
    shadow: {
        sm: null,
        md: null,
    },
});

export const darkTheme = createTheme(vars, {
    color: {
        bg: "#0f1117",
        bgSurface: "#1a1d27",
        bgSurfaceHover: "#232733",
        bgSurfaceActive: "#2c3040",
        text: "#e1e4ed",
        textMuted: "#8b90a0",
        textInverse: "#0f1117",
        border: "#2c3040",
        borderMuted: "#232733",
        primary: "#6c8cff",
        primaryHover: "#5a7aff",
        primaryText: "#ffffff",
        danger: "#ff6b6b",
        dangerHover: "#ff5252",
        dangerText: "#ffffff",
        success: "#51cf66",
        successText: "#ffffff",
        warning: "#fcc419",
        warningText: "#1a1d27",
        editorBg: "#1e2030",
        editorGutter: "#171924",
        editorActiveLine: "#252840",
        editorSelection: "#3d4470",
        editorCursor: "#e1e4ed",
        syntaxComment: "#636d83",
        syntaxKeyword: "#c792ea",
        syntaxProperty: "#82aaff",
        syntaxString: "#c3e88d",
        syntaxOperator: "#89ddff",
    },
    space: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
    },
    radius: {
        sm: "4px",
        md: "8px",
        lg: "12px",
    },
    fontSize: {
        xs: "11px",
        sm: "12px",
        md: "14px",
        lg: "16px",
        xl: "20px",
        xxl: "28px",
    },
    shadow: {
        sm: "0 1px 3px rgba(0, 0, 0, 0.3)",
        md: "0 4px 12px rgba(0, 0, 0, 0.4)",
    },
});

export const lightTheme = createTheme(vars, {
    color: {
        bg: "#f5f6fa",
        bgSurface: "#ffffff",
        bgSurfaceHover: "#f0f1f5",
        bgSurfaceActive: "#e8e9ef",
        text: "#1a1d27",
        textMuted: "#6b7080",
        textInverse: "#ffffff",
        border: "#d8dae3",
        borderMuted: "#e8e9ef",
        primary: "#4c6ef5",
        primaryHover: "#3b5bdb",
        primaryText: "#ffffff",
        danger: "#e03131",
        dangerHover: "#c92a2a",
        dangerText: "#ffffff",
        success: "#2f9e44",
        successText: "#ffffff",
        warning: "#e67700",
        warningText: "#ffffff",
        editorBg: "#fafafa",
        editorGutter: "#f0f1f5",
        editorActiveLine: "#e8eaf0",
        editorSelection: "#c8d2f0",
        editorCursor: "#1a1d27",
        syntaxComment: "#a0a1a7",
        syntaxKeyword: "#a626a4",
        syntaxProperty: "#4078f2",
        syntaxString: "#50a14f",
        syntaxOperator: "#0184bc",
    },
    space: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
    },
    radius: {
        sm: "4px",
        md: "8px",
        lg: "12px",
    },
    fontSize: {
        xs: "11px",
        sm: "12px",
        md: "14px",
        lg: "16px",
        xl: "20px",
        xxl: "28px",
    },
    shadow: {
        sm: "0 1px 3px rgba(0, 0, 0, 0.08)",
        md: "0 4px 12px rgba(0, 0, 0, 0.12)",
    },
});

globalStyle("html, body", {
    backgroundColor: vars.color.bg,
    color: vars.color.text,
});
